### ISSUE TITLE
Update not available

### ISSUE THREAD

**Issue by mbaas2** [oleg-shilo/Favorites.vscode#9]
Hi Oleg, I'm not sure if this is an issue for you or if VSCode has a problem, but when I select click "Install another version" in Favorite's context-menu in VS' Extension Manager - that list doesn't offer 1.3.3 - so I can't easily install 1.3.3.

**Comment by oleg-shilo** [comment]
I guess a glitch happens on publishing this release. 
Fixed now.

Thank you for letting me know.

**Comment by mbaas2** [comment]
Thanks - but it still doesn't show it!

Perhaps Code caches some info there?

**Comment by oleg-shilo** [comment]
It did update it to the latest version for me. Tested it on another PC as well:

![image](https://user-images.githubusercontent.com/16729806/75608118-ce9b0a80-5b50-11ea-8904-775d5ad4b07e.png)

Not sure what is happening. 

If it does not fix itself then you have no choice but to install it from vsix: https://github.com/oleg-shilo/Favorites.vscode/releases

**Comment by mbaas2** [comment]
Aaaarg - sorry, my bad! I have glasses, yet sometimes they just do not help! ;-)

**Comment by oleg-shilo** [comment]
I know the feeling :)
